version: '3.8'

services:
  user-management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-management-container
    ports:
      - "5000:5000"
    depends_on:
      - postgresql  # Зависимость от контейнера с PostgreSQL
      - redis
    environment:
      - REDIS_HOST=redis_manager

  postgresql:
    image: postgres:latest
    restart: always
    container_name: postgresql-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379"



