version: '3.8'

services:
  user-management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-management-container
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://katsiaryna:123456789@8000:5432/db_base  # Переменные окружения для подключения к базе данных
      - REDIS_URL=redis://8001:6379
      # Другие переменные окружения, необходимые для вашего сервиса
    depends_on:
      - postgresql  # Зависимость от контейнера с PostgreSQL
      - redis  # Зависимость от контейнера с Redis

  postgresql:
    image: postgres:latest
    restart: always
    container_name: postgresql-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=db_name

  redis:
    image: redis:latest
    restart: always
    container_name: redis-container
    ports:
      - "6379:6379"

#volumes:
#  pgdata:  # Определение тома для данных PostgreSQL
#
#networks:
#  custom:
#    driver: bridge
