name: Python CI

on:
  push:
    branches:
      - feature-dev
  pull_request:
    branches:
      - feature-dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Copy secrets to .env
        run:
          echo "${{ secrets.ENV }}" > .env

      - name: Format with Black
        uses: rickstaa/action-black@v1
        with:
          black_args: "src"